apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wereport-site-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: wereport-site
    spec:
      containers:
      - name: wereport-site
        image: eu.gcr.io/slavayssiere-sandbox/wereport-site:0.0.2
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: wereport-site-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31082
      name: restapi
  selector:
    app: wereport-site
  type: LoadBalancer